---

- hosts: all
  become: true
  tasks: 

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

