---
- name: Update and Reboot Linux Hosts
  hosts: all
  become: yes
  tasks:
    - name: Update APT packages (Debian-based systems)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Update DNF packages (RedHat-based systems)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Check if a reboot is required (Debian-based)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_facts['os_family'] == "Debian"

    - name: Reboot the system if required (Debian-based)
      ansible.builtin.reboot:
      when: reboot_required.stat.exists

    - name: Reboot the system (RedHat-based)
      ansible.builtin.reboot:
      when: ansible_facts['os_family'] == "RedHat"

